### PR TITLE
Add Ruby 3.2 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
This probably passes after https://github.com/voxpupuli/beaker-rspec/pull/119

**Comment by ekohl** [comment]
It is a legitimate failure due to Ruby 3.2 changes.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/beaker-docker/pull/93 should address that.

**Comment by bastelfreak** [comment]
after this is merged, I would also like to update the CI matrix to make the new job the new required one.

**Review by smortex — APPROVED** [review]
Looks okay. My only concern is that as far as I tested it on FreeBSD, Puppet 6/7 does not work with Ruby 3.2 because `fast_gettext` is currently broken due to the usage of `untaint` [deprecated in ruby 2.7](https://github.com/ruby/ruby/pull/2476) (could not fix it correctly yet, so no PR at the moment).

Maybe defaulting to Ruby 3.2 will have some side effects with this for some of our gems and we will have to use 3.1 for them until this is fixed.

If we want consistency across all gems, I would rather suggest using 3.1 as the default version.

**Pull request merged**
